---
- name: Download and install Filebeat
  hosts: webservers
  become: true
  tasks:
   - name: DL the filebeat .deb file
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

   - name: Install filebeat .deb
     command: dpkg -i filebeat-7.4.0-amd64.deb

   - name: Drop filebeat.yml
     copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

   - name: Enable and Config the system module
     command: filebeat modules enable system

   - name: Setup filebeat
     command: filebeat setup

   - name: Start filebeat service
     command: service filebeat start

   - name: Enable service filebeat on boot
     systemd:
      name: filebeat
      enabled: yes
      
   - name: Start filebeat service
     command: service filebeat start

   - name: Enable service filebeat on boot
     systemd:
      name: filebeat
      enabled: yes
