---
- name: Download and Setup MetricBeat
  hosts: webservers
  become: true
  tasks:
   - name: download the metricbeats .deb file
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

   - name: install the metricbeats .deb file
     command: dpkg -i metricbeat-7.4.0-amd64.deb

   - name: copy the metricbeat config file to the webservers
     copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

   - name: enable docker
     command: metricbeat modules enable docker

   - name: run the metricbeat setup
     command: metricbeat setup

   - name: enable metric beat
     command: service metricbeat start

   - name: enable service metric beat on boot
     systemd:
      name: metricbeat
      enabled: yes
